const MISAResource = {
  FileName : 'employee.xlsx',
  DownLoad : 'download',

  VN: {
    Tooltip:{
        Message: "Thông báo",
        IdentityNumber : "Số chứng minh thư nhân dân",
        SearchData : "Tìm kiếm",
        Reload:"Tải lại trang",
        Export :"Xuất tệp",
        Import :"Chèn tệp ",
        Close : "Đóng"

    },
    Unselected : "Bỏ chọn",
    Selected : "Đã chọn",
    ExportAll :"Xuất tất cả dữ liệu",
    ExportCurrent :"Bản ghi đang xem",
    CompanyName: "CÔNG TY CỔ PHẦN MISA",
    IsCustomer: "Là khách hàng",
    IsSupplier: "Là nhà cung cấp",
    UserName: "Nguyễn Chí Mạnh",
    Employee: "Nhân viên",
    AddNewTitle: "Thêm mới nhân viên",
    Edit: "Sửa",
    Copy: "Nhân bản",
    PreviousPage: "Trước",
    NextPage: "Tiếp",
    Logout: "Đăng xuất",
    EmployeeNotEmpty: "Mã nhân viên  không được để trống,",
    DepartmentNotEmpty: "Mời chọn phòng ban,",
    FullNameNotEmpty: "Họ tên không được để trống,",
    EmailNotEmpty: "Email không được để trống",
    EmailNotValid: "Email không đúng định dạng",
    PhoneIsNumeric: "Điện thoại phải là số",
    PhoneIsNotEmpty: "Điện thoại không được để trống",
    PhoneIsValid: "Điện thoại phải đủ 10 số",
    DebitAmountIsNumeric: "Tiền nợ  phải là số",
    EmployeeInformation: "Thông tin nhân viên",
    DateNotValid: "Ngày sinh không hợp lệ",
    DateNotGreater: "Ngày sinh không lớn hơn ngày hiện tại",
    NotFoundRecord: "Không tồn tại bản ghi muốn tìm",
    HideDialogQuestion: "Dữ liệu đã bị thay đổi bạn có muốn cất không ?",
    EmployeeCode: "Mã",
    FullName: "Tên",
    PhoneNumber: "ĐT di động",
    Fax: "ĐT cố định",
    DateOfBirth: "Ngày sinh",
    Gender: "Giới tính",
    IdentityNumber: "Số CMTND",
    IdentityDate: "Ngày cấp",
    IdentityPlace: "Nơi cấp",
    DebitAmount: "Số tiền nợ",
    ValueInput: "Giá trị nhập vào",
    BankAddress: "Chi nhánh",
    BankName: "Tên ngân hàng",
    CreditNumber: "Tài khoản ngân hàng",
    Address: "Địa chỉ",
    PositionName: "Chức danh",
    DeleteQuestion: "Bạn có thực sự muốn xóa nhân viên ",
    DeleteMultipleQuestion:
      "Bạn có thực sự muốn xóa những nhân viên đã chọn không ",
    EmployeeCodeExist: "Mã nhân viên",
    IsExist: "Đã tồn tại trong hệ thống",
    Help: " Giúp",
    CancelBtn: "Hủy bỏ",
    Previous: "Quay lại",
    Next: "Tiếp tục",
    StopUsing: "Ngừng sử dụng",
    MultipleCommand: "Thực hiện hàng loạt",
    AddAndNew: "Cất và thêm mới",
    LoginSuccess: "Đăng nhập thành công",
    PlaceholderText: "Tìm theo mã, tên nhân viên",
    TableColumn: {
      EmployeeCode: "MÃ NHÂN VIÊN",
      EmployeeName: "TÊN NHÂN VIÊN",
      Gender: "GIỚI TÍNH",
      DateOfBirth: "NGÀY SINH",
      CreditNumber: "SỐ TÀI KHOẢN",
      PositionName: "CHỨC DANH",
      DepartmentName: "TÊN ĐƠN VỊ",
      BankName: "TÊN NGÂN HÀNG",
      BankAddress: "CHI NHÁNH TK NGÂN HÀNG",
      Status: "TÌNH TRẠNG",
      IdentityNumber: "Số CMND",
      Feature: "CHỨC NĂNG",
      Yes: "Có",
    },
    Import: {
      DownLoadHere: "Tải tập tin chứa tệp nhập khẩu ",
      DownLoadFileError: "Tải file dữ liệu nhập khẩu bị lỗi",
      RowImportValid: "Số dòng nhập khẩu thành công",
      RowImportNotValid: "Số dòng nhập khẩu không thành công",
      ImportResult: "Kết quả nhập khẩu",
      RowValid: " dòng hợp lệ",
      RowNotValid: " dòng không hợp lệ",
      ChoseFileImport: "Chọn dữ liệu đã chuẩn bị để nhập khẩu vào phần mềm",
      DownLoadEmptyFile:
        "Chưa có tệp mẫu để chuẩn bị dữ liệu? Tải tệp excel mẫu mà phần mềm cung cấp để chuẩn bị dữ liệu nhập khẩu ",
      Step: "Bước",
      Here: "Tại đây",
      CloseFormExcel: "closeFormExcel",

      Sidebar: [
        {
          name: "1.Chọn tệp nguồn",
          value: 0,
        },
        {
          name: "2.Kiểm tra dữ liệu",
          value: 1,
        },
        {
          name: "3.Kết quả nhập khẩu",
          value: 2,
        },
      ],
    },
    LayoutSideBar: {
      overview: "Tổng quan",
      cash: "Tiền mặt",
      deposits: "Tiền gửi",
      purchase: "Mua hàng",
      sell: "Bán hàng",
      employeeManager: "Quản lý nhân viên",
      warehouse: " Kho",
      tool: " Công cụ dụng cụ",
      assets: " Tài sản cố định",
      tax: "Thuế",
      price: "Giá thành",
      synthetic: "Tổng hợp",
      budget: "Ngân sách",
      report: "Báo cáo",
      analysis: "Phân tích tài chính",
    },
    Login: {
      VietNam: "Việt Nam",
      English: "English",
      VN: "VN",
      EN: "EN",
      UserNotEmpty: "Tài khoản không được để trống",
      PasswordNotEmpty: "Mật khẩu không được để trống",
      ForgotPassword: "Quên mật khẩu?",
      Login: " Đăng nhập",
      LoginWith: "Hoặc đăng nhập với",
      CopyWriterText: "Copyright © 2012 - 2024 MISA JSC",
      UsernamePlaceholder: "Số điện thoại/email",
    },

    GenderName: {
      Male: "Nam",
      Female: "Nữ",
      Other: "Khác",
    },
    GenderCode: {
      Male: 0,
      Female: 1,
      Other: 2,
    },
    Cancel: "Hủy",
    Add: "Cất",
    Sum: "Tổng số :",
    Records: "bản ghi",
  },
  EN: {
    Tooltip:{
        Message: "Notification",
        IdentityNumber : "Identity Number",
        SearchData : "Search",
        Reload:"Reload",
        Export :"Export File",
        Import :"Import File ",
        Close : "Close"

    },
    previous: "previous",
    next: "next",
    Unselected : "Unselected",
    Selected : "Selected",
    ExportAll :"Export All Data",
    ExportCurrent :"Export Current Record",
    CompanyName: "MISA Corporation",
    IsCustomer: "Is Customer",
    IsSupplier: "Is Supplier",
    UserName: "Nguyen Chi Manh",
    Employee: "Employee",
    AddNewTitle: "Add New Employee",
    Edit: "Edit",
    Copy: "Copy",
    PreviousPage: "Previous",
    NextPage: "Next",
    Logout: "Logout",
    EmployeeNotEmpty: "Employee code cannot be empty,",
    DepartmentNotEmpty: "Please select department,",
    FullNameNotEmpty: "Full name cannot be empty,",
    EmailNotEmpty: "Email cannot be empty",
    EmailNotValid: "Invalid email format",
    PhoneIsNumeric: "Phone must be numeric",
    PhoneIsNotEmpty: "Phone cannot be empty",
    PhoneIsValid: "Phone must have 10 digits",
    DebitAmountIsNumeric: "Debit amount must be numeric",
    EmployeeInformation: "Employee Information",
    DateNotValid: "Invalid date of birth",
    DateNotGreater: "Date of birth cannot be greater than current date",
    NotFoundRecord: "Record you're looking for doesn't exist",
    HideDialogQuestion: "Data has been changed, do you want to save?",
    EmployeeCode: "Code",
    FullName: "Name",
    PhoneNumber: "Mobile Phone",
    Fax: "Landline Phone",
    DateOfBirth: "Date of Birth",
    Gender: "Gender",
    IdentityNumber: "Identity Number",
    IdentityDate: "Issue Date",
    IdentityPlace: "Place of Issue",
    DebitAmount: "Debit Amount",
    ValueInput: "Input Value",
    BankAddress: "Branch",
    BankName: "Bank Name",
    CreditNumber: "Bank Account",
    Address: "Address",
    PositionName: "Position",
    DeleteQuestion: "Are you sure you want to delete employee ",
    DeleteMultipleQuestion:
      "Are you sure you want to delete selected employees ",
    EmployeeCodeExist: "Employee Code",
    IsExist: "Already exists in the system",
    Help: "Help",
    CancelBtn: "Cancel",
    Previous: "Back",
    Next: "Continue",
    StopUsing: "Stop Using",
    MultipleCommand: "Batch Execution",
    AddAndNew: "Save and Add New",
    LoginSuccess: "Login Successful",
    PlaceholderText: "Search by code, employee name",
    TableColumn: {
      EmployeeCode: "EMPLOYEE CODE",
      EmployeeName: "EMPLOYEE NAME",
      Gender: "GENDER",
      DateOfBirth: "DATE OF BIRTH",
      CreditNumber: "BANK ACCOUNT NUMBER",
      PositionName: "POSITION",
      DepartmentName: "DEPARTMENT NAME",
      BankName: "BANK NAME",
      BankAddress: "BANK BRANCH",
      Status: "STATUS",
      IdentityNumber: "Identity Number",
      Feature: "FEATURE",
      Yes: "Yes",
    },
    Import: {
      DownLoadHere: "Download file containing import data ",
      DownLoadFileError: "Download import data file error",
      RowImportValid: "Number of successful imports",
      RowImportNotValid: "Number of unsuccessful imports",
      ImportResult: "Import Result",
      RowValid: " valid rows",
      RowNotValid: " invalid rows",
      ChoseFileImport: "Choose prepared data to import into the software",
      DownLoadEmptyFile:
        "No sample file to prepare data? Download the sample excel file provided by the software to prepare import data",
      Step: "Step",
      Here: "Here",
      CloseFormExcel: "closeFormExcel",

      Sidebar: [
        {
          name: "1. Select source file",
          value: 0,
        },
        {
          name: "2. Check data",
          value: 1,
        },
        {
          name: "3. Import result",
          value: 2,
        },
      ],
      EmployeeNotEmpty: "Mã nhân viên không được để trống,",
      FullNameNotEmpty: "Họ tên không được để trống,",
      EmailNotValid: "Email không đúng định dạng",
      previous: "previous",
      next: "next",
      Login: {
        VietNam: "Việt Nam",
        English: "English",
        VN: "VN",
        EN: "EN",
        UserNotEmpty: "Username is required",
        PasswordNotEmpty: "Username is required",
        ForgotPassword: "Forgot password?",
        Login: " Login",
        LoginWith: "Login with",
        CopyWriterText: "Copyright © 2012 - 2024 MISA JSC",
        UsernamePlaceholder: "PhoneNumber/Email",
      },
    },
    LayoutSideBar: {
      overview: "Overview",
      cash: "Cash",
      deposits: "Deposits",
      purchase: "Purchase",
      sell: "Sell",
      employeeManager: "Employee Management",
      warehouse: " Warehouse",
      tool: " Tools",
      assets: " Fixed Assets",
      tax: "Tax",
      price: "Cost",
      synthetic: "Synthetic",
      budget: "Budget",
      report: "Report",
      analysis: "Financial Analysis",
    },
    Login: {
      VietNam: "Viet Nam",
      English: "English",
      VN: "VN",
      EN: "EN",
      UserNotEmpty: "Username cannot be empty",
      PasswordNotEmpty: "Password cannot be empty",
      ForgotPassword: "Forgot password?",
      Login: "Login",
      LoginWith: "Or login with",
      CopyWriterText: "Copyright © 2012 - 2024 MISA JSC",
      UsernamePlaceholder: "Phone number/email",
    },

    GenderName: {
      Male: "Male",
      Female: "Female",
      Other: "Other",
    },
    GenderCode: {
      Male: 0,
      Female: 1,
      Other: 2,
    },
    Cancel: "Cancel",
    Add: "Save",
    Sum: "Total :",
    Records: "records",
  },
  Token: {
    TokenNotExist: "Token không tồn tại",
  },
  TypeAdd: {
    Add: 1,
  },
  Table: {
    Positions: "Positions",
    Departments: "Departments",
  },

  Refs: [
    "FullName",
    "reset",
    "PhoneNumber",
    "Address",
    "BankName",
    "BankAdress",
    "Email",
    "IdentityNumber",
    "IdentityPlace",
    "CreditNumber",
  ],
  returnMessage: {
    addComplete: "Thành công! Thêm mới thành công",
    updateComplete: "Thành công! Thay đổi thành công",
    deleteComplete: "Thành công! Nhân viên đã bị xóa",
    notFoundUrl: "Đường dẫn không chính xác",
    severError: "Lỗi hệ thống",
    HasError: "Đã có lỗi xảy ra vui lòng liên Hệ MISA để được giải quyết",
    Unauthorized: "Truy cập bị từ chối",
    Forbidden: "Bạn đã bị chặn truy cập vào đường dẫn",
  },
  notice: {
    question: "question",
    information: "information",
    error: "error",
    warning: "warning",
    success: "success",
  },
  NameMode: {
    AddNew: "THÊM MỚI",
    Change: "THAY ĐỔI",
    Delete: "Xóa",
    DeleteMultiple: "Xóa nhiều",
  },
  TextBtn: {
    Close: "Đóng",
    Accept: "Đồng ý",
    None: "Không",
  },
  EmitFunction: {
    showToast: "showToast",
    loadData: "loadData",
    hideForm: "hideForm",
    hideDlg: "hideDlg",
    removeData: "removeData",
    deleteMultiple: "deleteMultiple",
    addData: "addData",
  },
  PageSize: [
    {
      text: "10 bản ghi trên 1 trang",
      value: 10,
    },
    {
      text: "20 bản ghi trên 1 trang",
      value: 20,
    },
    {
      text: "30 bản ghi trên 1 trang",
      value: 30,
    },
    {
      text: "40 bản ghi trên 1 trang",
      value: 40,
    },
    {
      text: "50 bản ghi trên 1 trang",
      value: 50,
    },
  ],
  Key:{
    KeyD: 'd',
    KeyS: 's',
    KeyE: 'e',
    Escape: 'Escape',
    NUM1: '1',
    Enter: 'Enter'

  }

  //hàm Định dạng tiền
  //cretedBy : NC Mạnh
  //CreatedAt : 5/12/2023
  //   formatCurrency () {
  //     // Xóa ký tự không phải số và chấp nhận số và dấu chấm
  //     let value = this.state.EmployeeSelect.DebitAmount;
  //     // Format giá trị số theo định dạng tiền tệ VND
  //     value = parseFloat(value).toLocaleString("vi-VN", {
  //       style: "currency",
  //       currency: "VND",
  //     });

  //     // Cập nhật giá trị đã định dạng vào biến formattedValue để hiển thị
  //     this.state.EmployeeSelect.DebitAmount = value;
  //   },
};

export default MISAResource;
